import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import {
  Category,
  Product,
  Supplier,
  SupplierProduct,
  User,
  Order,
  Coupon,
  Review,
  InventoryItem,
  PricingRule,
  ReturnRequest,
} from './types';

// Dev seed credentials - NEVER hardcode production passwords.
// Support: environment variable (CUSTOMER_PASSWORD) or random generated.
const CUSTOMER_PASSWORD = process.env.CUSTOMER_PASSWORD || crypto.randomUUID() + 'C7';
const CUSTOMER_HASH = bcrypt.hashSync(CUSTOMER_PASSWORD, 10);

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'cat-kitchen',
    name: 'Kitchen & Dining',
    slug: 'kitchen-dining',
    description: 'Smart chopper, airtight containers, oil sprayers & modular kitchen hacks',
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80',
    icon: 'UtensilsCrossed',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 'cat-gadgets',
    name: 'Smart Gadgets & Tech',
    slug: 'smart-gadgets',
    description: 'Rechargeable desk lamps, portable blenders, mini vacuums & viral tech',
    imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop&q=80',
    icon: 'Cpu',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 'cat-home',
    name: 'Home & Living',
    slug: 'home-living',
    description: 'LED sunset lamps, aromatic diffusers, aesthetic organizers & bed runners',
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80',
    icon: 'Home',
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 'cat-beauty',
    name: 'Beauty & Grooming',
    slug: 'beauty-grooming',
    description: 'Facial ice rollers, ultrasonic skin scrubbers, hair stylers & beard kits',
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&auto=format&fit=crop&q=80',
    icon: 'Sparkles',
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 'cat-mobile',
    name: 'Mobile Accessories',
    slug: 'mobile-accessories',
    description: 'Fast wireless chargers, 3-in-1 mag cables, gimbal stabilizers & holders',
    imageUrl: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=600&auto=format&fit=crop&q=80',
    icon: 'Smartphone',
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 'cat-fitness',
    name: 'Fitness & Sports',
    slug: 'fitness-sports',
    description: 'Resistance loop bands, acupressure yoga mats, shaker bottles & hand grips',
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
    icon: 'Dumbbell',
    sortOrder: 6,
    isActive: true,
  },
  {
    id: 'cat-car',
    name: 'Car & Bike Accessories',
    slug: 'car-bike',
    description: 'Solar aroma diffusers, high pressure washer nozzles, seat gap organizers',
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&auto=format&fit=crop&q=80',
    icon: 'Car',
    sortOrder: 7,
    isActive: true,
  },
  {
    id: 'cat-fashion',
    name: 'Fashion & Jewelry',
    slug: 'fashion-jewelry',
    description: 'Anti-tarnish minimalist chains, smart wallets, evil eye charms & sunglasses',
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80',
    icon: 'Gem',
    sortOrder: 8,
    isActive: true,
  },
  {
    id: 'cat-kids',
    name: 'Kids & Toys',
    slug: 'kids-toys',
    description: 'LCD writing pads, magnetic building tiles, plush nightlights & puzzles',
    imageUrl: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&auto=format&fit=crop&q=80',
    icon: 'Gamepad2',
    sortOrder: 9,
    isActive: true,
  },
  {
    id: 'cat-office',
    name: 'Office & Stationery',
    slug: 'office-stationery',
    description: 'Ergonomic mouse pads, cable management trays, dual-side desk mats',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80',
    icon: 'Briefcase',
    sortOrder: 10,
    isActive: true,
  },
];

export const SEED_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-deodap',
    name: 'DeoDap Wholesale Surat',
    slug: 'deodap-surat',
    code: 'DEODAP',
    status: 'ACTIVE',
    integrationType: 'MOCK_DEODAP',
    contactEmail: 'api-support@deodap.in',
    contactPhone: '+91 98250 11223',
    reliabilityScore: 96.2,
    avgDeliveryDays: 3.2,
    returnScore: 94.0,
    apiEndpoint: 'https://api.mock.deodap.com/v2',
    notes: 'Primary wholesale dropshipping warehouse located in Surat, Gujarat. Huge catalog of daily utility and viral products.',
  },
  {
    id: 'sup-meesho',
    name: 'Meesho Direct Hub',
    slug: 'meesho-direct',
    code: 'MEESHO',
    status: 'ACTIVE',
    integrationType: 'OFFICIAL_API',
    contactEmail: 'supplier-ops@meesho.com',
    contactPhone: '+91 80 6123 4567',
    reliabilityScore: 91.5,
    avgDeliveryDays: 4.8,
    returnScore: 89.0,
    apiEndpoint: 'https://reseller-api.meesho.com/v1',
    notes: 'Large pan-India supplier network with very low base costs but slightly higher return rates.',
  },
  {
    id: 'sup-bharat',
    name: 'BharatKart Express Logistics',
    slug: 'bharat-express',
    code: 'BHARAT_EXPRESS',
    status: 'ACTIVE',
    integrationType: 'MANUAL_PORTAL',
    contactEmail: 'dispatch@bharatexpress.co.in',
    contactPhone: '+91 11 4987 6543',
    reliabilityScore: 98.4,
    avgDeliveryDays: 2.1,
    returnScore: 97.5,
    apiEndpoint: 'https://portal.bharatexpress.co.in/vendor',
    notes: 'Premium Delhi NCR & Mumbai bonded fulfillment center. Express dispatch in 24 hours, higher wholesale cost.',
  },
];

export const SEED_USERS: User[] = [
  {
    id: 'usr-customer-1',
    email: 'customer@bharatcart.in',
    passwordHash: CUSTOMER_HASH,
    name: 'Aarav Patel',
    phone: '+91 98234 56789',
    role: 'CUSTOMER',
    createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-customer-2',
    email: 'priya.sharma@example.com',
    passwordHash: CUSTOMER_HASH,
    name: 'Priya Sharma',
    phone: '+91 99887 76655',
    role: 'CUSTOMER',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-customer-3',
    email: 'rohit.verma@example.com',
    passwordHash: CUSTOMER_HASH,
    name: 'Rohit Verma',
    phone: '+91 91234 56780',
    role: 'CUSTOMER',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'usr-customer-4',
    email: 'ananya.deshmukh@example.com',
    passwordHash: CUSTOMER_HASH,
    name: 'Ananya Deshmukh',
    phone: '+91 94567 89012',
    role: 'CUSTOMER',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_ADDRESSES = [
  {
    id: 'addr-1',
    userId: 'usr-customer-1',
    fullName: 'Aarav Patel',
    phone: '+91 98234 56789',
    street: 'Flat 402, Lotus Residency, SG Highway',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380054',
    landmark: 'Near Palladium Mall',
    isDefault: true,
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
  {
    id: 'addr-2',
    userId: 'usr-customer-2',
    fullName: 'Priya Sharma',
    phone: '+91 99887 76655',
    street: 'B-1204, Cyber City Heights, DLF Phase 2',
    city: 'Gurugram',
    state: 'Haryana',
    pincode: '122002',
    landmark: 'Opposite Cyber Hub',
    isDefault: true,
    createdAt: new Date(Date.now() - 24 * 86400000).toISOString(),
  },
  {
    id: 'addr-3',
    userId: 'usr-customer-3',
    fullName: 'Rohit Verma',
    phone: '+91 91234 56780',
    street: 'Plot 77, 4th Cross, Koramangala 5th Block',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560095',
    landmark: 'Behind Sony Signal',
    isDefault: true,
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
];

export const SEED_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'DESI50',
    discountAmount: 50,
    minOrderValue: 499,
    isActive: true,
    usedCount: 142,
  },
  {
    id: 'coup-2',
    code: 'FIRST100',
    discountAmount: 100,
    minOrderValue: 899,
    isActive: true,
    usedCount: 89,
  },
  {
    id: 'coup-3',
    code: 'BHARAT15',
    discountPercent: 15,
    maxDiscount: 150,
    minOrderValue: 599,
    isActive: true,
    usedCount: 310,
  },
  {
    id: 'coup-4',
    code: 'FREESHIP',
    discountAmount: 49,
    minOrderValue: 299,
    isActive: true,
    usedCount: 520,
  },
];

export const SEED_PRICING_RULE: PricingRule = {
  defaultMarkupPercent: 38,
  fixedHandlingFee: 25,
  minMarginAmount: 80,
  freeShippingThreshold: 699,
  standardShippingFee: 49,
  codConvenienceFee: 39,
  categoryMarkupPercent: {
    'cat-gadgets': 45,
    'cat-beauty': 42,
    'cat-fashion': 55,
    'cat-kitchen': 35,
    'cat-home': 38,
  },
};

// Generates 52 realistic Indian ecommerce products across all 10 categories
export const RAW_PRODUCTS_DATA: Array<{
  id: string;
  title: string;
  slug: string;
  categoryId: string;
  mrp: number;
  sellingPrice: number;
  badge?: string;
  rating: number;
  reviewCount: number;
  isTrending: boolean;
  isBestSeller: boolean;
  isNewArrival: boolean;
  thumbnail: string;
  images: string[];
  description: string;
  shortDesc: string;
  specifications: Record<string, string>;
  // Supplier mapping base data
  deodapCost: number;
  meeshoCost: number;
  bharatCost: number;
}> = [
  // 1. Kitchen
  {
    id: 'prod-01',
    title: '4-in-1 Multifunctional Electric Handheld Vegetable Chopper & Slicer',
    slug: '4-in-1-electric-vegetable-chopper',
    categoryId: 'cat-kitchen',
    mrp: 999,
    sellingPrice: 429,
    badge: 'Viral TikTok',
    rating: 4.8,
    reviewCount: 348,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80',
    ],
    description: 'Effortlessly dice, slice, and mince garlic, chillies, ginger, and vegetables in seconds. Includes feeding hole for long veggies and one-touch cleaning with self-rinse feature.',
    shortDesc: 'Wireless portable kitchen chopper with fast USB-C charging and stainless steel blades.',
    specifications: { 'Blade Material': 'Food Grade Stainless Steel 304', 'Battery': '1200mAh USB Rechargeable', 'Motor': '40W High Torque', 'Capacity': '200ml Feeding Cup' },
    deodapCost: 195,
    meeshoCost: 180,
    bharatCost: 220,
  },
  {
    id: 'prod-02',
    title: 'Instant Kitchen Oil Spray Bottle for Healthy Air Fryer Cooking (200ml)',
    slug: 'instant-kitchen-oil-spray-bottle',
    categoryId: 'cat-kitchen',
    mrp: 499,
    sellingPrice: 229,
    badge: 'Diet Essential',
    rating: 4.6,
    reviewCount: 189,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80'],
    description: 'Precision fan-mist sprayer gives uniform oil coating with 70% less oil consumption. Perfect for roti, dosas, salads, baking, and air-fryers.',
    shortDesc: 'Anti-clog food-safe glass oil dispenser bottle with ergonomic trigger pump.',
    specifications: { 'Material': 'Lead-free Borosilicate Glass & BPA-free Nozzle', 'Volume': '200ml', 'Spray Type': 'Ultrafine Horizontal Mist' },
    deodapCost: 85,
    meeshoCost: 78,
    bharatCost: 110,
  },
  {
    id: 'prod-03',
    title: 'Automatic Water Can Dispenser Pump with LED Touch Control',
    slug: 'automatic-water-can-dispenser-pump',
    categoryId: 'cat-kitchen',
    mrp: 699,
    sellingPrice: 319,
    badge: 'Best Seller',
    rating: 4.7,
    reviewCount: 612,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=600&auto=format&fit=crop&q=80'],
    description: 'Universal fit for 20L standard Bisleri/Kinley bubble top cans. One touch dispenses 600ml or continuous flow. Fully wireless with 30-day battery life.',
    shortDesc: 'Rechargeable automatic drinking water bottle pump for home and office.',
    specifications: { 'Battery': '1200mAh Li-ion', 'Pipe': 'Food-grade Silicone 55cm', 'Certification': 'RoHS & CE Certified' },
    deodapCost: 140,
    meeshoCost: 135,
    bharatCost: 165,
  },
  {
    id: 'prod-04',
    title: 'Silicone Stretch Lids 6-Pack Reusable Airtight Food Covers',
    slug: 'silicone-stretch-lids-6-pack',
    categoryId: 'cat-kitchen',
    mrp: 399,
    sellingPrice: 179,
    badge: 'Eco Friendly',
    rating: 4.5,
    reviewCount: 94,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=600&auto=format&fit=crop&q=80'],
    description: 'Eliminate plastic cling wraps forever. Stretchable silicone lids fit bowls, cut watermelons, pots, mugs, and jars of any round or rectangular shape.',
    shortDesc: 'Microwave & freezer safe leakproof silicone bowl covers.',
    specifications: { 'Pieces': '6 Sizes (6.5cm to 21cm)', 'Temperature Range': '-40°C to 230°C', 'BPA Free': '100% Platinum Food Grade Silicone' },
    deodapCost: 65,
    meeshoCost: 59,
    bharatCost: 85,
  },
  {
    id: 'prod-05',
    title: 'Manual Stainless Steel Dumpling & Gujiya Maker Press Mold',
    slug: 'manual-dumpling-gujiya-press-mold',
    categoryId: 'cat-kitchen',
    mrp: 599,
    sellingPrice: 269,
    badge: 'Festival Special',
    rating: 4.4,
    reviewCount: 140,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=600&auto=format&fit=crop&q=80'],
    description: 'Double-headed dumpling maker machine. Press two momos or gujiyas simultaneously with perfect crimped edges in 1 second.',
    shortDesc: '2-in-1 automatic momo and dumpling wrapper press.',
    specifications: { 'Body': 'ABS Plastic + SUS 304 Stainless Steel', 'Anti-slip Base': 'Rubber Grippers Included' },
    deodapCost: 115,
    meeshoCost: 108,
    bharatCost: 140,
  },

  // 2. Gadgets & Tech
  {
    id: 'prod-06',
    title: 'Sunset Projection Lamp 16 Colors RGB with Smart Remote Control',
    slug: 'sunset-projection-lamp-rgb-remote',
    categoryId: 'cat-gadgets',
    mrp: 1299,
    sellingPrice: 499,
    badge: 'Gen-Z Favorite',
    rating: 4.9,
    reviewCount: 840,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80',
    ],
    description: 'Transform your room into a golden hour paradise. 16 static color modes, 4 gradient modes, 360-degree rotatable metal neck, crystal optical lens.',
    shortDesc: 'Aesthetic ambient mood projection night light for Instagram reels and bedroom decor.',
    specifications: { 'Lens': 'Optical Crystal Glass', 'Power': 'USB 5V/2A Cable with switch', 'Remote': '24-Key IR Controller' },
    deodapCost: 210,
    meeshoCost: 195,
    bharatCost: 250,
  },
  {
    id: 'prod-07',
    title: 'Portable USB Rechargeable Mini Juicer Blender Bottle (380ml)',
    slug: 'portable-mini-juicer-blender-bottle',
    categoryId: 'cat-gadgets',
    mrp: 1499,
    sellingPrice: 599,
    badge: 'Gym Essential',
    rating: 4.7,
    reviewCount: 420,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1570831739427-4467d0257353?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1570831739427-4467d0257353?w=600&auto=format&fit=crop&q=80'],
    description: 'Blend smoothies, protein shakes, and fresh fruit juices anywhere. 6-blade 3D stainless steel system easily crushes soft fruits and ice chips.',
    shortDesc: 'Wireless travel smoothie maker with magnetic induction safety switch.',
    specifications: { 'Battery': '2000mAh Lithium Rechargeable', 'RPM': '22,000 RPM', 'Capacity': '380ml Tritan Cup' },
    deodapCost: 270,
    meeshoCost: 255,
    bharatCost: 310,
  },
  {
    id: 'prod-08',
    title: 'Astronaut Galaxy Star Projector with Nebula Cloud & Remote',
    slug: 'astronaut-galaxy-star-projector',
    categoryId: 'cat-gadgets',
    mrp: 2499,
    sellingPrice: 1199,
    badge: 'Viral Hit',
    rating: 4.9,
    reviewCount: 520,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80'],
    description: '360° magnetic astronaut head projection angle. Projects hypnotic starry night sky and colorful moving nebula clouds onto your ceiling.',
    shortDesc: 'Stunning spaceman laser room projector with timer and customizable speed.',
    specifications: { 'Laser Wavelength': '532nm', 'Control Distance': '5m IR Remote', 'Modes': '8 Nebula Effects + Twinkling Stars' },
    deodapCost: 590,
    meeshoCost: 560,
    bharatCost: 650,
  },
  {
    id: 'prod-09',
    title: 'Multifunctional Wireless Charger Station 3-in-1 with Alarm & Night Light',
    slug: '3-in-1-multifunction-wireless-charger-station',
    categoryId: 'cat-gadgets',
    mrp: 2199,
    sellingPrice: 949,
    badge: 'Desktop Hero',
    rating: 4.6,
    reviewCount: 210,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1622445262464-84b1456045b6?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1622445262464-84b1456045b6?w=600&auto=format&fit=crop&q=80'],
    description: 'Charges Phone, Smartwatch, and TWS Earbuds simultaneously on one tidy stand. Built-in digital clock and soft warm breathing lamp.',
    shortDesc: '15W Fast Qi certified dock for iPhone, Samsung, AirPods & Apple Watch.',
    specifications: { 'Output': '15W / 10W / 7.5W / 5W', 'Port': 'Type-C QuickCharge 3.0', 'Protection': 'Foreign Object & Overheat Sensors' },
    deodapCost: 480,
    meeshoCost: 465,
    bharatCost: 540,
  },
  {
    id: 'prod-10',
    title: 'Handheld High-Speed Turbo Jet Mini Fan (130,000 RPM Blower)',
    slug: 'turbo-jet-mini-handheld-fan',
    categoryId: 'cat-gadgets',
    mrp: 1899,
    sellingPrice: 799,
    badge: 'Summer Essential',
    rating: 4.7,
    reviewCount: 165,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format&fit=crop&q=80'],
    description: 'Pocket-sized tornado! Extreme wind speed reaches up to 52m/s. Doubles as PC keyboard dust cleaner, barbecue charcoal blower, and personal cooling device.',
    shortDesc: 'Metal CNC turbine brushless motor blower with stepless dial speed control.',
    specifications: { 'Motor': 'Brushless 130,000 RPM', 'Wind Speed': '52 m/s Max', 'Battery': '3000mAh Dual 18650 cells' },
    deodapCost: 410,
    meeshoCost: 395,
    bharatCost: 460,
  },

  // 3. Home & Living
  {
    id: 'prod-11',
    title: 'Flame Aroma Diffuser & Ultrasonic Cool Mist Humidifier',
    slug: 'flame-aroma-diffuser-humidifier',
    categoryId: 'cat-home',
    mrp: 1599,
    sellingPrice: 649,
    badge: 'Aesthetic Decor',
    rating: 4.8,
    reviewCount: 390,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=80'],
    description: 'Realistic fireplace flame simulation using warm amber LEDs and ultrasonic mist. Add pure essential oils for relaxing aromatherapy and dry air relief.',
    shortDesc: '200ml whisper-quiet desk flame humidifier with automatic waterless shutoff.',
    specifications: { 'Mist Output': '20-30ml/hr', 'Noise': '< 25dB Silent Run', 'Safety': 'Auto Power-Off Sensor' },
    deodapCost: 310,
    meeshoCost: 295,
    bharatCost: 360,
  },
  {
    id: 'prod-12',
    title: 'Motion Sensor LED Strip Light for Wardrobe & Staircase (3 Meters)',
    slug: 'motion-sensor-led-strip-light',
    categoryId: 'cat-home',
    mrp: 899,
    sellingPrice: 389,
    badge: 'Smart Home',
    rating: 4.6,
    reviewCount: 275,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&auto=format&fit=crop&q=80'],
    description: 'Lights up automatically when human movement is detected in the dark. Magnetic adhesive backing attaches anywhere without drilling or wiring.',
    shortDesc: 'USB rechargeable warm white LED puck light with passive infrared sensor.',
    specifications: { 'Sensor Angle': '120° Wide Cone', 'Detection Distance': '3-5 Meters', 'Modes': 'Always On / Night Sensor Mode' },
    deodapCost: 175,
    meeshoCost: 160,
    bharatCost: 205,
  },
  {
    id: 'prod-13',
    title: 'Nordic Foldable Dirty Clothes Laundry Hamper with Handles',
    slug: 'nordic-foldable-laundry-hamper',
    categoryId: 'cat-home',
    mrp: 699,
    sellingPrice: 299,
    badge: 'Space Saver',
    rating: 4.5,
    reviewCount: 142,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80'],
    description: 'Thick waterproof linen cotton fabric with reinforced dual handles. Folds flat in seconds when not in use for slim storage between washing machine gaps.',
    shortDesc: '75L Large capacity freestanding laundry basket with PE waterproof coating.',
    specifications: { 'Capacity': '75 Liters', 'Dimensions': '40 x 30 x 60 cm', 'Fabric': 'Natural Cotton Linen Blend' },
    deodapCost: 130,
    meeshoCost: 120,
    bharatCost: 155,
  },
  {
    id: 'prod-14',
    title: 'Aesthetic Clear Acrylic Weekly Dry Erase Planner Board with Stand',
    slug: 'acrylic-weekly-dry-erase-planner-board',
    categoryId: 'cat-home',
    mrp: 999,
    sellingPrice: 449,
    badge: 'Productivity',
    rating: 4.7,
    reviewCount: 98,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1584727638096-042c45049ebe?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1584727638096-042c45049ebe?w=600&auto=format&fit=crop&q=80'],
    description: 'Sleek minimalist desktop memo board illuminated by a warm LED wooden base. Comes with 7 colorful neon liquid chalk pens and micro-fiber eraser cloth.',
    shortDesc: 'Illuminated transparent glass-like acrylic to-do message board.',
    specifications: { 'Board': '5mm Cast Scratch-resistant Acrylic', 'Base': 'Natural Solid Beechwood with LED Strip' },
    deodapCost: 215,
    meeshoCost: 198,
    bharatCost: 245,
  },
  {
    id: 'prod-15',
    title: 'Multipurpose Double-Sided Nano Grip Tape Heavy Duty (5 Meters)',
    slug: 'heavy-duty-nano-grip-tape-5m',
    categoryId: 'cat-home',
    mrp: 399,
    sellingPrice: 169,
    badge: 'DIY Must-Have',
    rating: 4.6,
    reviewCount: 512,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&auto=format&fit=crop&q=80'],
    description: 'Holds wall frames, power extension strips, kitchen spice racks, and carpets without nails or residue. Washable with warm water to restore 100% stickiness.',
    shortDesc: 'Traceless removable reusable clear gel mounting tape.',
    specifications: { 'Thickness': '2.0mm', 'Width': '30mm', 'Weight Capacity': 'Holds up to 1kg on smooth tiles/walls' },
    deodapCost: 65,
    meeshoCost: 55,
    bharatCost: 80,
  },

  // 4. Beauty & Grooming
  {
    id: 'prod-16',
    title: 'Facial Ice Roller for Face & Eye Puffiness Relief (Silicone Mold)',
    slug: 'silicone-facial-ice-roller-mold',
    categoryId: 'cat-beauty',
    mrp: 499,
    sellingPrice: 199,
    badge: 'Skincare Viral',
    rating: 4.7,
    reviewCount: 310,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1512290900672-1f0239a03770?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1512290900672-1f0239a03770?w=600&auto=format&fit=crop&q=80'],
    description: 'Customize with rose water, cucumber slices, or green tea. Glides across cheekbones to tighten pores, contour jawlines, and brighten morning dark circles.',
    shortDesc: 'Unbreakable leakproof food-grade silicone cryotherapy facial massager.',
    specifications: { 'Material': 'Food-Grade BPA-Free Silicone', 'Capacity': '150ml Liquid' },
    deodapCost: 75,
    meeshoCost: 68,
    bharatCost: 95,
  },
  {
    id: 'prod-17',
    title: '5-in-1 Hot Air Styler Hair Dryer & Volumizer Brush Wand',
    slug: '5-in-1-hot-air-styler-wand',
    categoryId: 'cat-beauty',
    mrp: 2999,
    sellingPrice: 1299,
    badge: 'Best Seller',
    rating: 4.8,
    reviewCount: 650,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80'],
    description: 'Includes drying nozzle, left/right auto-wrap curling barrels, round volumizing blow dry comb, and straight paddle brush. Ceramic ionic coating eliminates frizz.',
    shortDesc: 'Salon-style negative ion hair blower and multi-barrel curler set.',
    specifications: { 'Power': '1000W High Speed Aerodynamic Motor', 'Heat Settings': '3 Temperature Controls', 'Cord': '360° Swivel 2-Meter Cable' },
    deodapCost: 680,
    meeshoCost: 640,
    bharatCost: 760,
  },
  {
    id: 'prod-18',
    title: 'Ultrasonic Skin Scrubber Deep Pore Blackhead Spatula',
    slug: 'ultrasonic-skin-scrubber-blackhead-spatula',
    categoryId: 'cat-beauty',
    mrp: 1499,
    sellingPrice: 599,
    badge: 'Dermatologist Pick',
    rating: 4.6,
    reviewCount: 220,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&auto=format&fit=crop&q=80'],
    description: '24,000Hz high-frequency vibration painlessly dislodges clogged sebum, makeup residue, and dead skin cells while enhancing serum absorption via ion pulses.',
    shortDesc: 'Rechargeable facial peeling scrubber with 4 cleansing and lifting modes.',
    specifications: { 'Spatula Blade': '100% Medical Stainless Steel', 'Vibration Frequency': '24,000 Hz Ultrasonic Waves' },
    deodapCost: 280,
    meeshoCost: 265,
    bharatCost: 320,
  },
  {
    id: 'prod-19',
    title: 'Rechargeable Professional Hair & Beard Trimmer Vintage T9 Blade',
    slug: 'vintage-t9-rechargeable-beard-hair-trimmer',
    categoryId: 'cat-beauty',
    mrp: 999,
    sellingPrice: 399,
    badge: 'Mens Grooming',
    rating: 4.7,
    reviewCount: 480,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1621607512214-68297480165e?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1621607512214-68297480165e?w=600&auto=format&fit=crop&q=80'],
    description: 'Full metal dragon embossed carving body with zero-gapped carbon steel T-blade for precise hair lining, neck fading, dry shaving, and beard detailing.',
    shortDesc: 'Cordless zero-gap detail clipper with 4 guide combs (1.5mm to 4mm).',
    specifications: { 'Battery': '1200mAh Lithium-ion (120 mins run)', 'Blade': 'Titanium Stainless Steel Zero-Cut' },
    deodapCost: 180,
    meeshoCost: 165,
    bharatCost: 215,
  },
  {
    id: 'prod-20',
    title: 'Electric Heated Eyelash Curler with Quick Preheat & Dual Temp Modes',
    slug: 'electric-heated-eyelash-curler',
    categoryId: 'cat-beauty',
    mrp: 699,
    sellingPrice: 289,
    badge: 'Quick Glam',
    rating: 4.5,
    reviewCount: 135,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&auto=format&fit=crop&q=80'],
    description: '10-second fast heating silicone pad gently curls lashes without pinching or crimping eyelids. Natural upward curve holds all day long for up to 24 hours.',
    shortDesc: 'Type-C rechargeable curved heated lash styling wand.',
    specifications: { 'Heating Pad': 'Sensing Temperature Color-change Silicone', 'Levels': '65°C & 85°C Modes' },
    deodapCost: 120,
    meeshoCost: 110,
    bharatCost: 145,
  },

  // 5. Mobile Accessories
  {
    id: 'prod-21',
    title: 'Universal 360° Rotatable Long Arm Bedside Phone & Tablet Lazy Stand',
    slug: 'universal-long-arm-bedside-phone-tablet-stand',
    categoryId: 'cat-mobile',
    mrp: 899,
    sellingPrice: 379,
    badge: 'Binge Watcher',
    rating: 4.7,
    reviewCount: 390,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1586105251261-72a756497a11?w=600&auto=format&fit=crop&q=80'],
    description: 'Heavy duty carbon steel dual articulated arms stay rock solid without sagging. Clamps firmly to bed headboards, study desks, and kitchen counters.',
    shortDesc: 'Flexible metal scissor arm clamp holder for 4.7 to 12.9 inch iPads & phones.',
    specifications: { 'Clamp Width': 'Up to 7.5cm surfaces', 'Compatibility': 'All 4.5" - 11" Devices', 'Material': 'Magnesium Aluminium Alloy' },
    deodapCost: 170,
    meeshoCost: 155,
    bharatCost: 200,
  },
  {
    id: 'prod-22',
    title: 'MagSafe Magnetic Ring Card Holder Kickstand Wallet for iPhone & Android',
    slug: 'magsafe-magnetic-card-holder-kickstand-wallet',
    categoryId: 'cat-mobile',
    mrp: 799,
    sellingPrice: 329,
    badge: 'Pocket Upgrade',
    rating: 4.6,
    reviewCount: 160,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=600&auto=format&fit=crop&q=80'],
    description: 'Strong N52 rare-earth magnets hold up to 3 cards with RFID blocking shield. Integrated zinc alloy hinge flips out into portrait FaceTime or landscape Netflix stand.',
    shortDesc: 'Ultra-slim leather magnetic phone wallet with adjustable angle stand.',
    specifications: { 'Magnet Strength': '3800 Gauss N52 Magnets', 'Capacity': '3 Debit/Credit Cards or ID', 'Material': 'Premium Vegan PU Leather' },
    deodapCost: 145,
    meeshoCost: 135,
    bharatCost: 175,
  },
  {
    id: 'prod-23',
    title: '3-in-1 Glowing Streamer LED Fast Charging Cable (Type-C, Micro, Lightning)',
    slug: '3-in-1-glowing-streamer-led-charging-cable',
    categoryId: 'cat-mobile',
    mrp: 499,
    sellingPrice: 199,
    badge: 'Cool Light',
    rating: 4.5,
    reviewCount: 410,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80'],
    description: 'Mesmerizing electric flow animation visualizes current moving through the cable in the dark. 3 universal ends charge all your gadgets simultaneously.',
    shortDesc: 'Visible flow light 1.2M multi-connector nylon braided charging wire.',
    specifications: { 'Output': '3.0A Max Speed', 'Connectors': 'USB-A to Type-C + Lightning + Micro USB', 'Length': '1.2 Meters' },
    deodapCost: 78,
    meeshoCost: 70,
    bharatCost: 98,
  },
  {
    id: 'prod-24',
    title: 'Smart AI Face Tracking 360° Auto Gimbal Tripod for Content Creators',
    slug: 'smart-ai-face-tracking-auto-gimbal-tripod',
    categoryId: 'cat-mobile',
    mrp: 2499,
    sellingPrice: 1099,
    badge: 'Content Creator',
    rating: 4.8,
    reviewCount: 290,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1580910051074-3eb694886505?w=600&auto=format&fit=crop&q=80'],
    description: 'No app needed! Built-in wide-angle AI camera recognizes face and body gesture controls: OK sign to start tracking, Open Palm to pause. Follows you smoothly.',
    shortDesc: 'Rechargeable 360-degree rotation smart auto-following selfie robot mount.',
    specifications: { 'Battery': '1200mAh (6-8 hours shooting)', 'AI Camera': 'Ultra-fast 30fps Realtime Tracking' },
    deodapCost: 520,
    meeshoCost: 490,
    bharatCost: 590,
  },

  // 6. Fitness & Sports
  {
    id: 'prod-25',
    title: '11-Piece Heavy Duty Resistance Bands Set with Door Anchor & Ankle Straps',
    slug: '11-piece-resistance-bands-gym-set',
    categoryId: 'cat-fitness',
    mrp: 1499,
    sellingPrice: 599,
    badge: 'Home Workout',
    rating: 4.8,
    reviewCount: 520,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=600&auto=format&fit=crop&q=80'],
    description: 'Replaces full dumbbell racks! 5 stackable natural latex resistance tubes providing up to 150 lbs total tension for chest, arms, shoulders, back, and leg workouts.',
    shortDesc: 'Complete home gym strength training kit with travel carry pouch.',
    specifications: { 'Tension Bands': '10, 20, 30, 40, 50 lbs', 'Material': '100% Malaysian Natural Elastic Latex' },
    deodapCost: 260,
    meeshoCost: 240,
    bharatCost: 310,
  },
  {
    id: 'prod-26',
    title: 'Electric Protein Shaker Bottle Vortex Mixer (Tritan 650ml)',
    slug: 'electric-protein-shaker-vortex-mixer',
    categoryId: 'cat-fitness',
    mrp: 1299,
    sellingPrice: 549,
    badge: 'Zero Lumps',
    rating: 4.7,
    reviewCount: 310,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80'],
    description: 'No more vigorous manual shaking or unmixed protein powder clumps. Powerful 7000 RPM motorized blunt blade whips milkshakes and pre-workouts in 15 seconds.',
    shortDesc: 'Rechargeable self-stirring blender mug with measurement markings.',
    specifications: { 'Motor Speed': '7,000 RPM Vortex Whirlwind', 'Battery': '1200mAh USB-C', 'Material': 'BPA-Free Infant Grade Tritan' },
    deodapCost: 250,
    meeshoCost: 235,
    bharatCost: 290,
  },
  {
    id: 'prod-27',
    title: 'Adjustable Hand Grip Strengthener with Digital Counter (10-100 kg)',
    slug: 'adjustable-hand-grip-strengthener-counter',
    categoryId: 'cat-fitness',
    mrp: 499,
    sellingPrice: 229,
    badge: 'Top Rated',
    rating: 4.6,
    reviewCount: 440,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&auto=format&fit=crop&q=80'],
    description: 'Dial tension easily adjusts resistance from 10kg up to 100kg. Mechanical clicker logs completed repetitions automatically. Builds forearm veins and grip.',
    shortDesc: 'Heavy-duty steel spring wrist and forearm muscle developer.',
    specifications: { 'Resistance Range': '10kg to 100kg Dial Spring', 'Grip': 'Ergonomic TPR Non-slip Handle' },
    deodapCost: 95,
    meeshoCost: 88,
    bharatCost: 120,
  },
  {
    id: 'prod-28',
    title: 'Lotus Spike Acupressure Mat and Neck Pillow Set for Back Pain Relief',
    slug: 'lotus-acupressure-mat-pillow-set',
    categoryId: 'cat-fitness',
    mrp: 1799,
    sellingPrice: 749,
    badge: 'Pain Relief',
    rating: 4.8,
    reviewCount: 285,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=600&auto=format&fit=crop&q=80'],
    description: 'Lie down for 20 minutes to release endorphins, relieve lumbar sciatica stiffness, boost blood circulation, and cure insomnia. Thousands of non-toxic acupoints.',
    shortDesc: 'Therapeutic needle massage cushion with matching cervical neck pillow.',
    specifications: { 'Spikes': 'Over 8,000 Precision Pressure Points', 'Inner': 'High Density Eco Foam', 'Cover': '100% Breathable Linen' },
    deodapCost: 350,
    meeshoCost: 330,
    bharatCost: 410,
  },

  // 7. Car & Bike
  {
    id: 'prod-29',
    title: 'Solar Helicopter Dashboard Rotating Aroma Air Freshener',
    slug: 'solar-helicopter-rotating-car-air-freshener',
    categoryId: 'cat-car',
    mrp: 799,
    sellingPrice: 349,
    badge: 'Cool Car Gadget',
    rating: 4.7,
    reviewCount: 390,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&auto=format&fit=crop&q=80'],
    description: 'Propeller spins dynamically in sunlight without batteries or charging cables. Solid beechwood ring diffuses long-lasting ocean and cologne scent rings.',
    shortDesc: 'Zinc alloy aviation model solar fragrance diffuser for car dashboards.',
    specifications: { 'Power': 'Monocrystalline Solar Panel', 'Material': 'High Strength Electroplated Alloy' },
    deodapCost: 150,
    meeshoCost: 140,
    bharatCost: 180,
  },
  {
    id: 'prod-30',
    title: 'High Pressure Brass Water Gun Hose Nozzle for Car & Garden Washing',
    slug: 'high-pressure-brass-hose-nozzle',
    categoryId: 'cat-car',
    mrp: 599,
    sellingPrice: 249,
    badge: 'Power Clean',
    rating: 4.6,
    reviewCount: 620,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?w=600&auto=format&fit=crop&q=80'],
    description: 'Twist the solid brass head to switch between powerful pinpoint jet stream for muddy tires and gentle wide conical shower for washing windshields or watering gardens.',
    shortDesc: 'Rust-proof 100% heavy solid brass quick connector spray nozzle.',
    specifications: { 'Material': 'Pure Solid Brass', 'Connector': 'Standard 1/2 Inch Quick Hose Coupling' },
    deodapCost: 105,
    meeshoCost: 95,
    bharatCost: 130,
  },
  {
    id: 'prod-31',
    title: 'Car Seat Gap Storage Box Organizer with Dual USB Charger Ports',
    slug: 'car-seat-gap-organizer-dual-usb',
    categoryId: 'cat-car',
    mrp: 999,
    sellingPrice: 429,
    badge: 'Clean Car',
    rating: 4.5,
    reviewCount: 175,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&auto=format&fit=crop&q=80'],
    description: 'Stops coins, smartphones, and keys from slipping into the hard-to-reach seat cracks. Adds dedicated cup holder, sunglass pocket, and two quick charge USB ports.',
    shortDesc: 'Premium PU leather console drop-catcher caddy with cigarette plug power.',
    specifications: { 'Material': 'Microfiber Leather + ABS', 'Ports': 'Dual 5V/2.4A USB Ports' },
    deodapCost: 195,
    meeshoCost: 180,
    bharatCost: 230,
  },

  // 8. Fashion & Jewelry
  {
    id: 'prod-32',
    title: 'Waterproof Anti-Tarnish Minimalist Herringbone Snake Chain Necklace',
    slug: 'anti-tarnish-herringbone-snake-chain-gold',
    categoryId: 'cat-fashion',
    mrp: 999,
    sellingPrice: 349,
    badge: '18K PVD Plated',
    rating: 4.9,
    reviewCount: 490,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80'],
    description: 'Wear in the shower, pool, or gym without turning green or fading. Vacuum PVD 18K gold plating on surgical stainless steel. Hypoallergenic and sweatproof.',
    shortDesc: 'Chic everyday layering flat snake choker for women and men.',
    specifications: { 'Base': '316L Surgical Stainless Steel', 'Plating': '18K PVD Gold Electroplating', 'Length': '40cm + 5cm Extension' },
    deodapCost: 130,
    meeshoCost: 120,
    bharatCost: 165,
  },
  {
    id: 'prod-33',
    title: 'Smart Pop-Up RFID Blocking Aluminum Automatic Card Holder Wallet',
    slug: 'smart-popup-rfid-card-holder-wallet',
    categoryId: 'cat-fashion',
    mrp: 899,
    sellingPrice: 349,
    badge: 'Cyber Shield',
    rating: 4.8,
    reviewCount: 580,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80'],
    description: 'Click the bottom trigger slider and all cards fan out systematically for instant access. Blocks digital pickpocketing and wireless skimming.',
    shortDesc: 'Aviation-grade aluminum slim card case with carbon fiber magnetic cash clip.',
    specifications: { 'Capacity': '5-6 Credit Cards + Cash Notes', 'Protection': '13.56 MHz RFID/NFC Blocking' },
    deodapCost: 140,
    meeshoCost: 130,
    bharatCost: 175,
  },
  {
    id: 'prod-34',
    title: 'Retro Square Aviator Sunglasses UV400 Polarized Metal Frame',
    slug: 'retro-square-aviator-sunglasses-polarized',
    categoryId: 'cat-fashion',
    mrp: 1299,
    sellingPrice: 499,
    badge: 'Bollywood Style',
    rating: 4.7,
    reviewCount: 230,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80'],
    description: 'Classic Tony Stark / Kabir Singh inspired square wire frame. TAC 9-layer polarized lenses filter harsh road glares and provide 100% UVA/UVB protection.',
    shortDesc: 'Unisex luxury metal shades with spring hinges and silicon nose rests.',
    specifications: { 'Lens': 'TAC Triacetate Polarized UV400', 'Frame': 'Corrosion-resistant Nickel Silver Alloy' },
    deodapCost: 200,
    meeshoCost: 185,
    bharatCost: 240,
  },

  // 9. Kids & Toys
  {
    id: 'prod-35',
    title: '8.5-Inch LCD Writing Tablet & Digital Drawing Doodle Pad',
    slug: 'lcd-writing-tablet-doodle-drawing-pad',
    categoryId: 'cat-kids',
    mrp: 499,
    sellingPrice: 199,
    badge: 'Screen-Free Fun',
    rating: 4.6,
    reviewCount: 710,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&auto=format&fit=crop&q=80'],
    description: 'Paperless learning toy for toddlers. Write and draw with stylus, one button clears entire screen instantly. Lock switch prevents accidental erasure.',
    shortDesc: 'Eye-protection pressure sensitive electronic slate for children.',
    specifications: { 'Screen Size': '8.5 Inch Flexible LCD', 'Battery': 'CR2025 Replaceable Coin Cell (1 Year life)' },
    deodapCost: 80,
    meeshoCost: 72,
    bharatCost: 100,
  },
  {
    id: 'prod-36',
    title: 'Squishy Silicone Duck Touch Sensor Night Light for Kids Bedside',
    slug: 'squishy-silicone-duck-sensor-night-light',
    categoryId: 'cat-kids',
    mrp: 999,
    sellingPrice: 429,
    badge: 'Super Cute',
    rating: 4.9,
    reviewCount: 360,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80'],
    description: 'Squeeze or tap its belly to toggle between dim sleeping light and bright ambient lamp. Soft BPA-free silicone also works as a cute phone stand with its long rubber feet.',
    shortDesc: 'Rechargeable dimmable animal night light with 30-min auto off timer.',
    specifications: { 'Battery': '1200mAh USB-C', 'Material': 'Food-Grade Squishy Silicone' },
    deodapCost: 190,
    meeshoCost: 178,
    bharatCost: 225,
  },
  {
    id: 'prod-37',
    title: 'Magnetic Building Blocks 3D Magnetic Tiles Set for Kids (40 Pcs)',
    slug: 'magnetic-building-tiles-set-40pcs',
    categoryId: 'cat-kids',
    mrp: 1799,
    sellingPrice: 799,
    badge: 'STEM Education',
    rating: 4.8,
    reviewCount: 220,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&auto=format&fit=crop&q=80'],
    description: 'Build castles, rocket ships, towers, and geometry solids. Strong ultrasonic welded magnets safely enclosed inside transparent colorful ABS plastic tiles.',
    shortDesc: 'Creative 3D magnet geometric constructor blocks with guide booklet.',
    specifications: { 'Pieces': '40 Assorted Geometric Shapes', 'Safety': 'Non-toxic BPA Free Round Edges' },
    deodapCost: 380,
    meeshoCost: 350,
    bharatCost: 440,
  },

  // 10. Office & Stationery
  {
    id: 'prod-38',
    title: 'Dual-Sided Waterproof Leather Extended Desk Pad Mouse Mat (80x40 cm)',
    slug: 'dual-sided-leather-extended-desk-pad-mat',
    categoryId: 'cat-office',
    mrp: 799,
    sellingPrice: 349,
    badge: 'Work From Home',
    rating: 4.7,
    reviewCount: 480,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80'],
    description: 'Two colors in one pad! Flip between Midnight Blue and Warm Camel Yellow. Spill-proof oil-resistant surface wipes clean with a damp cloth in one second.',
    shortDesc: 'Large anti-fray desk blotter for laptop, keyboard, and mouse gliding.',
    specifications: { 'Size': '80cm x 40cm x 2mm', 'Material': 'Eco Friendly PU Leather' },
    deodapCost: 145,
    meeshoCost: 135,
    bharatCost: 175,
  },
  {
    id: 'prod-39',
    title: 'Ergonomic Foldable Aluminum Laptop Riser Stand with 7 Height Levels',
    slug: 'ergonomic-foldable-aluminum-laptop-stand',
    categoryId: 'cat-office',
    mrp: 999,
    sellingPrice: 389,
    badge: 'Spine Health',
    rating: 4.8,
    reviewCount: 620,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80'],
    description: 'Elevates laptop screen to natural eye level to prevent cervical neck hunching and wrist strain. Hollow open ventilation design prevents laptop thermal throttling.',
    shortDesc: 'Portable heavy duty aluminium alloy folding notebook riser.',
    specifications: { 'Weight Capacity': 'Supports up to 20kg', 'Compatibility': 'All 10" to 15.6" MacBooks & PCs' },
    deodapCost: 175,
    meeshoCost: 160,
    bharatCost: 210,
  },
  {
    id: 'prod-40',
    title: 'Magnetic Cable Management Organizer Clips Pack of 3 with Adhesive Base',
    slug: 'magnetic-cable-clips-pack-of-3',
    categoryId: 'cat-office',
    mrp: 399,
    sellingPrice: 179,
    badge: 'Desk Zen',
    rating: 4.6,
    reviewCount: 195,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80'],
    description: 'Keeps charging cords from falling behind your nightstand or work desk. Snap cables into magnetic beads that dock smoothly onto the slim weighted basebar.',
    shortDesc: 'Universal wire clamp keeper for lightning, USB-C, and HDMI cords.',
    specifications: { 'Base': 'Traceless 3M Acrylic Adhesive Bar', 'Beads': 'Strong Neodymium Magnetic Buckles' },
    deodapCost: 70,
    meeshoCost: 62,
    bharatCost: 88,
  },

  // Additional viral products to ensure deep product catalog (>50 items)
  {
    id: 'prod-41',
    title: 'Smart Temperature Display Vacuum Insulated Flask Bottle (500ml)',
    slug: 'smart-temperature-display-vacuum-flask-500ml',
    categoryId: 'cat-kitchen',
    mrp: 799,
    sellingPrice: 329,
    badge: 'Hot / Cold',
    rating: 4.7,
    reviewCount: 420,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80'],
    description: 'Touch the lid cap to view the liquid temperature on a bright HD LCD screen. Double-wall vacuum insulation keeps tea scalding hot for 12 hours or iced water cold for 24 hours.',
    shortDesc: '304 Stainless steel thermos with waterproof digital thermal touch lid.',
    specifications: { 'Insulation': 'Double Wall SUS304 Stainless Steel', 'Capacity': '500ml' },
    deodapCost: 140,
    meeshoCost: 130,
    bharatCost: 170,
  },
  {
    id: 'prod-42',
    title: 'Wireless Electric Cleaning Brush Scrubber with 3 Interchangeable Heads',
    slug: 'wireless-electric-spin-cleaning-brush-scrubber',
    categoryId: 'cat-home',
    mrp: 1199,
    sellingPrice: 479,
    badge: 'Cleaning Hack',
    rating: 4.8,
    reviewCount: 310,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&auto=format&fit=crop&q=80'],
    description: 'Motorized high torque rotating head scrubs grime off bathroom tile grout, kitchen stovetops, sink basins, and sofa stains with zero manual elbow grease.',
    shortDesc: 'Waterproof handheld electric rotary scouring wand with USB charging.',
    specifications: { 'Motor Speed': '350 RPM Powerful Torque', 'Heads': 'Nylon Brush + Sponge Pad + Cashmere Polisher' },
    deodapCost: 220,
    meeshoCost: 205,
    bharatCost: 260,
  },
  {
    id: 'prod-43',
    title: 'Mini Portable Handheld Heat Sealer for Food Snack Bags',
    slug: 'mini-portable-handheld-heat-sealer',
    categoryId: 'cat-kitchen',
    mrp: 399,
    sellingPrice: 159,
    badge: 'Snack Saver',
    rating: 4.5,
    reviewCount: 520,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&auto=format&fit=crop&q=80'],
    description: 'Reseal opened potato chips, dry fruit bags, and biscuits in 3 seconds to keep them crispy fresh. Built-in mini razor blade also cuts bags open effortlessly.',
    shortDesc: '2-in-1 pocket plastic pouch sealer with magnetic fridge holder.',
    specifications: { 'Heating': 'Rapid Micro Thermal Strip', 'Battery': '2x AA Battery Powered' },
    deodapCost: 65,
    meeshoCost: 58,
    bharatCost: 82,
  },
  {
    id: 'prod-44',
    title: 'Magnetic Floating Moon Lamp with 3 Lighting Colors & Touch Base',
    slug: 'magnetic-levitating-floating-moon-lamp',
    categoryId: 'cat-home',
    mrp: 4999,
    sellingPrice: 2199,
    badge: 'Luxury Decor',
    rating: 4.9,
    reviewCount: 160,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1532767153582-b1a0e5145009?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1532767153582-b1a0e5145009?w=600&auto=format&fit=crop&q=80'],
    description: 'Floating in mid-air via electromagnetic levitation! The 3D printed lunar globe spins slowly without touching the base while receiving power wirelessly.',
    shortDesc: 'Hypnotic levitating 14cm 3D moon sphere with touch wood pedestal.',
    specifications: { 'Levitation Height': '15mm Air Gap', 'Modes': 'Warm Yellow, Cool White, Neutral Glow' },
    deodapCost: 1150,
    meeshoCost: 1090,
    bharatCost: 1280,
  },
  {
    id: 'prod-45',
    title: 'Bluetooth Anti-Lost GPS Smart Tracker Tag for Keys, Wallet & Luggage',
    slug: 'bluetooth-anti-lost-smart-tracker-tag',
    categoryId: 'cat-gadgets',
    mrp: 699,
    sellingPrice: 289,
    badge: 'Never Lose',
    rating: 4.6,
    reviewCount: 380,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80'],
    description: 'Ring your keys from your phone with a loud 90dB buzzer, or double press the tag to make your silent phone ring. Crowdsourced location map tracks last lost spot.',
    shortDesc: 'Ultra compact Bluetooth 5.2 keyfinder finder beacon for Android & iOS.',
    specifications: { 'Battery': 'CR2032 (10-12 months standby)', 'Buzzer': '90dB High Pitch Beeper' },
    deodapCost: 110,
    meeshoCost: 100,
    bharatCost: 135,
  },
  {
    id: 'prod-46',
    title: 'Spill-Proof Gyroscope 360° Rotating Baby Feeding Bowl',
    slug: 'spill-proof-gyroscope-rotating-baby-bowl',
    categoryId: 'cat-kids',
    mrp: 499,
    sellingPrice: 219,
    badge: 'Parenting Miracle',
    rating: 4.7,
    reviewCount: 420,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1576158113928-4c240eaaf360?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1576158113928-4c240eaaf360?w=600&auto=format&fit=crop&q=80'],
    description: 'Internal dish rotates 360 degrees using planetary gravity gyroscopic motion to keep snacks face up no matter how toddlers toss or swing it.',
    shortDesc: 'UFO planet style unspillable snack bowl with lid for toddlers.',
    specifications: { 'Material': '100% Food Grade Polypropylene (BPA Free)', 'Dishwasher': 'Top Rack Safe' },
    deodapCost: 85,
    meeshoCost: 76,
    bharatCost: 105,
  },
  {
    id: 'prod-47',
    title: 'Automatic Touchless Infrared Foam Soap Dispenser (350ml)',
    slug: 'automatic-touchless-foam-soap-dispenser',
    categoryId: 'cat-kitchen',
    mrp: 999,
    sellingPrice: 429,
    badge: 'Hygienic',
    rating: 4.7,
    reviewCount: 290,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80'],
    description: 'Waves of rich micro-bubble lather dispensed in 0.25 seconds without touching germy pumps. Saves 50% handwash soap by mixing 1:4 with water.',
    shortDesc: 'Waterproof IPX4 smart sensor automatic foaming hand soap pump.',
    specifications: { 'Sensor Speed': '0.25 Seconds Infrared Sensing', 'Battery': 'Rechargeable Li-ion 1200mAh' },
    deodapCost: 190,
    meeshoCost: 175,
    bharatCost: 225,
  },
  {
    id: 'prod-48',
    title: 'Electric Eyebrow Epilator & Facial Hair Remover Pen with LED',
    slug: 'electric-eyebrow-epilator-trimmer-pen',
    categoryId: 'cat-beauty',
    mrp: 599,
    sellingPrice: 249,
    badge: 'Painless',
    rating: 4.6,
    reviewCount: 540,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80'],
    description: 'Shape eyebrows with absolute precision. 18K gold plated micro-tip glides gently against skin to remove fine peach fuzz without redness, cuts, or irritation.',
    shortDesc: 'Lipstick sized instant painless eyebrow shaper with built-in spotlight.',
    specifications: { 'Tip': '18K Hypoallergenic Gold Plated Head', 'Power': 'USB Rechargeable' },
    deodapCost: 100,
    meeshoCost: 90,
    bharatCost: 125,
  },
  {
    id: 'prod-49',
    title: 'Car Windshield Sun Shade Umbrella Foldable UV Heat Reflector',
    slug: 'car-windshield-sun-shade-umbrella-foldable',
    categoryId: 'cat-car',
    mrp: 899,
    sellingPrice: 389,
    badge: 'Beat The Heat',
    rating: 4.8,
    reviewCount: 380,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&auto=format&fit=crop&q=80'],
    description: 'Opens and closes just like a regular umbrella! Titanium silver peptide coating reflects 99% of sun rays to protect dashboards from cracking and keep interiors cool.',
    shortDesc: 'Heavy duty 10-rib skeleton folding car front window sun umbrella.',
    specifications: { 'Coating': 'Titanium Silver UPF 50+', 'Size': 'Universal 140cm x 79cm' },
    deodapCost: 175,
    meeshoCost: 162,
    bharatCost: 210,
  },
  {
    id: 'prod-50',
    title: 'Minimalist Natural Wooden Docking Station & Bedside Nightstand Valet',
    slug: 'wooden-docking-station-nightstand-valet',
    categoryId: 'cat-office',
    mrp: 1499,
    sellingPrice: 649,
    badge: 'Gentleman Gift',
    rating: 4.8,
    reviewCount: 190,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    thumbnail: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&auto=format&fit=crop&q=80'],
    description: 'Crafted from solid seasoned ash wood. Neatly parks phone, smart watch, wallet, keys, coins, reading glasses, and pens in one organized place.',
    shortDesc: 'Handcrafted eco wooden desktop caddy with cable routing channels.',
    specifications: { 'Wood': 'Solid Walnut Finish Hardwood', 'Assembly': 'Tool-free interlocking pieces' },
    deodapCost: 290,
    meeshoCost: 275,
    bharatCost: 350,
  },
  {
    id: 'prod-51',
    title: 'Waterproof Magnetic Bluetooth Shower Speaker with Suction Cup',
    slug: 'waterproof-magnetic-bluetooth-shower-speaker',
    categoryId: 'cat-gadgets',
    mrp: 1299,
    sellingPrice: 529,
    badge: 'IPX7 Waterproof',
    rating: 4.7,
    reviewCount: 340,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80'],
    description: 'Sing your heart out! Completely submersible IPX7 waterproof rating with rich punchy bass and colorful rhythm LED ring. Heavy silicone suction sticks to bathroom tiles.',
    shortDesc: '5W Wireless bathroom speaker with built-in microphone for calls.',
    specifications: { 'Water Resistance': 'IPX7 Submersible 1 Meter', 'Battery': '1000mAh (8 hours playtime)' },
    deodapCost: 230,
    meeshoCost: 215,
    bharatCost: 280,
  },
  {
    id: 'prod-52',
    title: 'Multifunctional Collapsible Vegetable Washing & Draining Cutting Board',
    slug: 'collapsible-vegetable-washing-cutting-board',
    categoryId: 'cat-kitchen',
    mrp: 699,
    sellingPrice: 289,
    badge: 'Smart Kitchen',
    rating: 4.6,
    reviewCount: 410,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    thumbnail: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&auto=format&fit=crop&q=80'],
    description: '3-in-1 kitchen miracle: expands into an 11-liter vegetable soaking tub with bottom drain plug, collapses down into a durable food-grade chopping board.',
    shortDesc: 'Space saving foldable silicone sink colander and prep board.',
    specifications: { 'Material': 'Food Grade PP + TPR Silicone', 'Drainage': 'One-click Bottom Water Stopper' },
    deodapCost: 125,
    meeshoCost: 115,
    bharatCost: 150,
  },
];

export function generateSeedDatabase() {
  const categories = [...SEED_CATEGORIES];
  const suppliers = [...SEED_SUPPLIERS];
  const users = [...SEED_USERS];
  const addresses = [...SEED_ADDRESSES];
  const coupons = [...SEED_COUPONS];
  const pricingRule = { ...SEED_PRICING_RULE };

  const products: Product[] = [];
  const supplierProducts: SupplierProduct[] = [];
  const inventory: InventoryItem[] = [];
  const reviews: Review[] = [];

  RAW_PRODUCTS_DATA.forEach((raw) => {
    const cat = categories.find((c) => c.id === raw.categoryId);
    const product: Product = {
      id: raw.id,
      title: raw.title,
      slug: raw.slug,
      description: raw.description,
      shortDesc: raw.shortDesc,
      categoryId: raw.categoryId,
      categorySlug: cat ? cat.slug : 'kitchen-dining',
      categoryName: cat ? cat.name : 'General',
      mrp: raw.mrp,
      sellingPrice: raw.sellingPrice,
      images: raw.images,
      thumbnail: raw.thumbnail,
      badge: raw.badge,
      rating: raw.rating,
      reviewCount: raw.reviewCount,
      isTrending: raw.isTrending,
      isBestSeller: raw.isBestSeller,
      isNewArrival: raw.isNewArrival,
      isActive: true,
      specifications: raw.specifications,
      warrantyInfo: '7-Day Easy Replacement Guarantee',
      codAvailable: true,
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
      updatedAt: new Date().toISOString(),
    };
    products.push(product);

    // Supplier 1: DeoDap (Surat)
    supplierProducts.push({
      id: `sp-${raw.id}-deodap`,
      supplierId: 'sup-deodap',
      productId: raw.id,
      externalProductId: `DD-${raw.id.toUpperCase()}-X`,
      costPrice: raw.deodapCost,
      shippingCost: 45,
      stock: 120,
      isAvailable: true,
      leadTimeDays: 3,
      lastSyncedAt: new Date().toISOString(),
    });

    // Supplier 2: Meesho Direct
    supplierProducts.push({
      id: `sp-${raw.id}-meesho`,
      supplierId: 'sup-meesho',
      productId: raw.id,
      externalProductId: `MEE-${raw.id.toUpperCase()}-IN`,
      costPrice: raw.meeshoCost,
      shippingCost: 55,
      stock: 85,
      isAvailable: true,
      leadTimeDays: 5,
      lastSyncedAt: new Date().toISOString(),
    });

    // Supplier 3: Bharat Express (Premium/Fast)
    supplierProducts.push({
      id: `sp-${raw.id}-bharat`,
      supplierId: 'sup-bharat',
      productId: raw.id,
      externalProductId: `BEX-${raw.id.toUpperCase()}-PRIO`,
      costPrice: raw.bharatCost,
      shippingCost: 35,
      stock: 250,
      isAvailable: true,
      leadTimeDays: 2,
      lastSyncedAt: new Date().toISOString(),
    });

    // Inventory record per supplier
    inventory.push({
      id: `inv-${raw.id}-deodap`,
      productId: raw.id,
      supplierId: 'sup-deodap',
      productTitle: raw.title,
      supplierName: 'DeoDap Wholesale Surat',
      totalStock: 120,
      reservedStock: 4,
      availableStock: 116,
      lowStockAlert: 15,
      updatedAt: new Date().toISOString(),
    });
    inventory.push({
      id: `inv-${raw.id}-bharat`,
      productId: raw.id,
      supplierId: 'sup-bharat',
      productTitle: raw.title,
      supplierName: 'BharatKart Express Logistics',
      totalStock: 250,
      reservedStock: 10,
      availableStock: 240,
      lowStockAlert: 20,
      updatedAt: new Date().toISOString(),
    });

    // Sample verified review
    reviews.push({
      id: `rev-${raw.id}-1`,
      productId: raw.id,
      userId: 'usr-customer-2',
      userName: 'Priya S.',
      rating: 5,
      title: 'Super fast delivery and fantastic build quality!',
      comment: 'Ordered this last Thursday and got it on Saturday. Works exactly as described. Worth every rupee.',
      verifiedPurchase: true,
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    });
  });

  // Sample historical orders across different order statuses
  const orders: Order[] = [
    {
      id: 'ord-10041',
      orderNumber: 'BC-10041',
      userId: 'usr-customer-1',
      customerName: 'Aarav Patel',
      customerEmail: 'customer@bharatcart.in',
      customerPhone: '+91 98234 56789',
      addressId: 'addr-1',
      shippingAddress: {
        fullName: 'Aarav Patel',
        phone: '+91 98234 56789',
        street: 'Flat 402, Lotus Residency, SG Highway',
        city: 'Ahmedabad',
        state: 'Gujarat',
        pincode: '380054',
        landmark: 'Near Palladium Mall',
      },
      status: 'DELIVERED',
      subtotal: 1098,
      shippingFee: 0,
      discount: 100,
      couponCode: 'FIRST100',
      totalAmount: 998,
      estimatedProfit: 438,
      paymentMethod: 'UPI_MANUAL',
      createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      items: [
        {
          id: 'oi-1',
          orderId: 'ord-10041',
          productId: 'prod-01',
          productTitle: '4-in-1 Multifunctional Electric Handheld Vegetable Chopper & Slicer',
          productThumbnail: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&auto=format&fit=crop&q=80',
          quantity: 1,
          unitPrice: 429,
          totalPrice: 429,
          supplierCost: 195,
          selectedSupplier: 'DeoDap Wholesale Surat',
          selectedSupplierId: 'sup-deodap',
        },
        {
          id: 'oi-2',
          orderId: 'ord-10041',
          productId: 'prod-11',
          productTitle: 'Flame Aroma Diffuser & Ultrasonic Cool Mist Humidifier',
          productThumbnail: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=80',
          quantity: 1,
          unitPrice: 649,
          totalPrice: 649,
          supplierCost: 310,
          selectedSupplier: 'DeoDap Wholesale Surat',
          selectedSupplierId: 'sup-deodap',
        },
      ],
      payments: [
        {
          id: 'pay-1',
          orderId: 'ord-10041',
          method: 'UPI_MANUAL',
          status: 'COMPLETED',
          amount: 998,
          currency: 'INR',
          transactionRef: 'UPI-UTR-324908129841',
          upiPayerVpa: 'aarav@okicici',
          verifiedBy: 'usr-admin',
          verifiedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
          createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
        },
      ],
      shipments: [
        {
          id: 'shp-1',
          orderId: 'ord-10041',
          carrier: 'Delhivery Surface Express',
          trackingNumber: 'DEL-992144021',
          currentStatus: 'Package delivered at doorstep with signature',
          deliveredAt: new Date(Date.now() - 2 * 86400000).toISOString(),
          createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
        },
      ],
      statusLogs: [
        { id: 'log-1', orderId: 'ord-10041', toStatus: 'PENDING_PAYMENT', note: 'Order initiated with UPI', actorRole: 'CUSTOMER', createdAt: new Date(Date.now() - 7 * 86400000).toISOString() },
        { id: 'log-2', orderId: 'ord-10041', fromStatus: 'PENDING_PAYMENT', toStatus: 'PAID', note: 'Payment verified via UTR 324908129841', actorRole: 'ADMIN', createdAt: new Date(Date.now() - 7 * 86400000).toISOString() },
        { id: 'log-3', orderId: 'ord-10041', fromStatus: 'PAID', toStatus: 'SUPPLIER_ORDERED', note: 'Automated order sent to DeoDap #DD-9021', actorRole: 'SYSTEM', createdAt: new Date(Date.now() - 6 * 86400000).toISOString() },
        { id: 'log-4', orderId: 'ord-10041', fromStatus: 'SUPPLIER_ORDERED', toStatus: 'SHIPPED', note: 'Dispatched via Delhivery DEL-992144021', actorRole: 'SUPPLIER', createdAt: new Date(Date.now() - 4 * 86400000).toISOString() },
        { id: 'log-5', orderId: 'ord-10041', fromStatus: 'SHIPPED', toStatus: 'DELIVERED', note: 'Successfully delivered to customer', actorRole: 'SYSTEM', createdAt: new Date(Date.now() - 2 * 86400000).toISOString() },
      ],
      supplierOrders: [
        {
          id: 'so-1',
          orderId: 'ord-10041',
          supplierId: 'sup-deodap',
          supplierName: 'DeoDap Wholesale Surat',
          externalOrderId: 'DD-ORD-98014',
          status: 'DELIVERED',
          wholesaleCost: 505,
          shippingCharged: 45,
          trackingNumber: 'DEL-992144021',
          carrier: 'Delhivery Express',
          createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
          updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
        },
      ],
    },
    {
      id: 'ord-10042',
      orderNumber: 'BC-10042',
      userId: 'usr-customer-2',
      customerName: 'Priya Sharma',
      customerEmail: 'priya.sharma@example.com',
      customerPhone: '+91 99887 76655',
      addressId: 'addr-2',
      shippingAddress: {
        fullName: 'Priya Sharma',
        phone: '+91 99887 76655',
        street: 'B-1204, Cyber City Heights, DLF Phase 2',
        city: 'Gurugram',
        state: 'Haryana',
        pincode: '122002',
        landmark: 'Opposite Cyber Hub',
      },
      status: 'SHIPPED',
      subtotal: 1199,
      shippingFee: 0,
      discount: 50,
      couponCode: 'DESI50',
      totalAmount: 1149,
      estimatedProfit: 469,
      paymentMethod: 'UPI_MANUAL',
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      updatedAt: new Date().toISOString(),
      items: [
        {
          id: 'oi-3',
          orderId: 'ord-10042',
          productId: 'prod-08',
          productTitle: 'Astronaut Galaxy Star Projector with Nebula Cloud & Remote',
          productThumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
          quantity: 1,
          unitPrice: 1199,
          totalPrice: 1199,
          supplierCost: 590,
          selectedSupplier: 'DeoDap Wholesale Surat',
          selectedSupplierId: 'sup-deodap',
        },
      ],
      payments: [
        {
          id: 'pay-2',
          orderId: 'ord-10042',
          method: 'UPI_MANUAL',
          status: 'COMPLETED',
          amount: 1149,
          currency: 'INR',
          transactionRef: 'UPI-UTR-891048201948',
          upiPayerVpa: 'priya@okhdfcbank',
          verifiedBy: 'usr-admin',
          verifiedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
          createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
        },
      ],
      shipments: [
        {
          id: 'shp-2',
          orderId: 'ord-10042',
          carrier: 'BlueDart Air',
          trackingNumber: 'BLU-8819204',
          currentStatus: 'In Transit - Out for delivery at Delhi-NCR Hub',
          estimatedDelivery: new Date(Date.now() + 86400000).toISOString(),
          shippedAt: new Date(Date.now() - 86400000).toISOString(),
          createdAt: new Date(Date.now() - 86400000).toISOString(),
        },
      ],
      statusLogs: [
        { id: 'log-20', orderId: 'ord-10042', toStatus: 'PAID', note: 'UPI payment verified', actorRole: 'ADMIN', createdAt: new Date(Date.now() - 2 * 86400000).toISOString() },
        { id: 'log-21', orderId: 'ord-10042', fromStatus: 'PAID', toStatus: 'SUPPLIER_ORDERED', note: 'Supplier routing chose DeoDap for lowest landed cost', actorRole: 'SYSTEM', createdAt: new Date(Date.now() - 36 * 3600000).toISOString() },
        { id: 'log-22', orderId: 'ord-10042', fromStatus: 'SUPPLIER_ORDERED', toStatus: 'SHIPPED', note: 'Airway Bill generated BLU-8819204', actorRole: 'SUPPLIER', createdAt: new Date(Date.now() - 12 * 3600000).toISOString() },
      ],
      supplierOrders: [
        {
          id: 'so-2',
          orderId: 'ord-10042',
          supplierId: 'sup-deodap',
          supplierName: 'DeoDap Wholesale Surat',
          externalOrderId: 'DD-ORD-98442',
          status: 'SHIPPED',
          wholesaleCost: 590,
          shippingCharged: 45,
          trackingNumber: 'BLU-8819204',
          carrier: 'BlueDart Air',
          createdAt: new Date(Date.now() - 36 * 3600000).toISOString(),
          updatedAt: new Date().toISOString(),
        },
      ],
    },
    {
      id: 'ord-10043',
      orderNumber: 'BC-10043',
      userId: 'usr-customer-3',
      customerName: 'Rohit Verma',
      customerEmail: 'rohit.verma@example.com',
      customerPhone: '+91 91234 56780',
      addressId: 'addr-3',
      shippingAddress: {
        fullName: 'Rohit Verma',
        phone: '+91 91234 56780',
        street: 'Plot 77, 4th Cross, Koramangala 5th Block',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560095',
      },
      status: 'PAYMENT_REVIEW',
      subtotal: 599,
      shippingFee: 49,
      discount: 0,
      totalAmount: 648,
      estimatedProfit: 268,
      paymentMethod: 'UPI_MANUAL',
      createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
      updatedAt: new Date().toISOString(),
      items: [
        {
          id: 'oi-4',
          orderId: 'ord-10043',
          productId: 'prod-07',
          productTitle: 'Portable USB Rechargeable Mini Juicer Blender Bottle (380ml)',
          productThumbnail: 'https://images.unsplash.com/photo-1570831739427-4467d0257353?w=600&auto=format&fit=crop&q=80',
          quantity: 1,
          unitPrice: 599,
          totalPrice: 599,
          supplierCost: 255,
          selectedSupplier: 'Meesho Direct Hub',
          selectedSupplierId: 'sup-meesho',
        },
      ],
      payments: [
        {
          id: 'pay-3',
          orderId: 'ord-10043',
          method: 'UPI_MANUAL',
          status: 'UNDER_REVIEW',
          amount: 648,
          currency: 'INR',
          transactionRef: 'UTR-991204812490',
          upiPayerVpa: 'rohit@paytm',
          createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
        },
      ],
      shipments: [],
      statusLogs: [
        { id: 'log-30', orderId: 'ord-10043', toStatus: 'PENDING_PAYMENT', note: 'Awaiting UPI transfer', actorRole: 'CUSTOMER', createdAt: new Date(Date.now() - 4 * 3600000).toISOString() },
        { id: 'log-31', orderId: 'ord-10043', fromStatus: 'PENDING_PAYMENT', toStatus: 'PAYMENT_REVIEW', note: 'Customer submitted UTR UTR-991204812490', actorRole: 'CUSTOMER', createdAt: new Date(Date.now() - 3 * 3600000).toISOString() },
      ],
      supplierOrders: [],
    },
    {
      id: 'ord-10044',
      orderNumber: 'BC-10044',
      userId: 'usr-customer-1',
      customerName: 'Aarav Patel',
      customerEmail: 'customer@bharatcart.in',
      customerPhone: '+91 98234 56789',
      addressId: 'addr-1',
      shippingAddress: {
        fullName: 'Aarav Patel',
        phone: '+91 98234 56789',
        street: 'Flat 402, Lotus Residency, SG Highway',
        city: 'Ahmedabad',
        state: 'Gujarat',
        pincode: '380054',
      },
      status: 'SUPPLIER_SELECTION',
      subtotal: 499,
      shippingFee: 49,
      discount: 0,
      totalAmount: 548,
      estimatedProfit: 254,
      paymentMethod: 'MOCK_GATEWAY',
      createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
      updatedAt: new Date().toISOString(),
      items: [
        {
          id: 'oi-5',
          orderId: 'ord-10044',
          productId: 'prod-06',
          productTitle: 'Sunset Projection Lamp 16 Colors RGB with Smart Remote Control',
          productThumbnail: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80',
          quantity: 1,
          unitPrice: 499,
          totalPrice: 499,
          supplierCost: 210,
        },
      ],
      payments: [
        {
          id: 'pay-4',
          orderId: 'ord-10044',
          method: 'MOCK_GATEWAY',
          status: 'COMPLETED',
          amount: 548,
          currency: 'INR',
          transactionRef: 'PAY_MOCK_8829104',
          createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
        },
      ],
      shipments: [],
      statusLogs: [
        { id: 'log-40', orderId: 'ord-10044', toStatus: 'PAID', note: 'Instant sandbox payment approved', actorRole: 'SYSTEM', createdAt: new Date(Date.now() - 2 * 3600000).toISOString() },
        { id: 'log-41', orderId: 'ord-10044', fromStatus: 'PAID', toStatus: 'SUPPLIER_SELECTION', note: 'Evaluating best supplier route based on landed cost and delivery time', actorRole: 'SYSTEM', createdAt: new Date(Date.now() - 100 * 60000).toISOString() },
      ],
      supplierOrders: [],
    },
  ];

  // Sample return request
  const returnRequests: ReturnRequest[] = [
    {
      id: 'ret-1',
      orderId: 'ord-10041',
      orderNumber: 'BC-10041',
      orderItemId: 'oi-1',
      productTitle: '4-in-1 Multifunctional Electric Handheld Vegetable Chopper & Slicer',
      userId: 'usr-customer-1',
      userName: 'Aarav Patel',
      reason: 'DEFECTIVE_OR_DAMAGED',
      description: 'The blade rotation slows down under pressure. Would love a replacement.',
      status: 'REQUESTED',
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 86400000).toISOString(),
    },
  ];

  return {
    categories,
    products,
    suppliers,
    supplierProducts,
    inventory,
    users,
    addresses,
    orders,
    coupons,
    reviews,
    returnRequests,
    pricingRule,
  };
}
